dependencies {
  api(project(":keel-api"))

  implementation("org.jetbrains.kotlin:kotlin-reflect")
  implementation("com.fasterxml.jackson.core:jackson-annotations")

  testImplementation(project(":keel-core"))
  testImplementation("tools.jackson.core:jackson-databind")
  testImplementation("tools.jackson.module:jackson-module-kotlin")
  testImplementation("io.strikt:strikt-core")
}
