shifts:
- startDate: Mon 13 Apr 2020
  user: ajordens
- startDate: Mon 20 Apr 2020
  user: cfieber
- startDate: Mon 27 Apr 2020
  user: ethanfrogers
- startDate: Mon 04 May 2020
  user: ezimanyi
- startDate: Mon 11 May 2020
  user: jonsie
- startDate: Mon 18 May 2020
  user: maggieneterval
- startDate: Mon 25 May 2020
  stopDate: Sun 31 May 2020
  user: plumpy
