shifts:
- startDate: Mon 01 Feb 2021
  user: ethanfrogers
- startDate: Mon 08 Feb 2021
  user: jonsie
- startDate: Mon 15 Feb 2021
  user: plumpy@google.com
- startDate: Mon 22 Feb 2021
  user: robzienert
- startDate: Mon 01 Mar 2021
  user: cfieber
- startDate: Mon 08 Mar 2021
  user: claymccoy
- startDate: Mon 15 Mar 2021
  user: ethanfrogers
- startDate: Mon 22 Mar 2021
  stopDate: Sun 28 Mar 2021
  user: jonsie
