===== Delete Amazon Load Balancer Description

====== Key

+deleteAmazonLoadBalancerDescription+

====== Description

This description provides the inputs necessary to handle the deletion of an Elastic Load Balancer at Amazon. This is a destructive process, which cannot be reversed.

CAUTION: This operation marks the end of a Load Balancer's life. The process cannot be undone, and the configuration cannot be reconstituted. A load balancer of the same configuration will need to be recreated from scratch.

====== Example Request Body
[source,javascript]
----
[{
    "deleteAmazonLoadBalancerDescription": {
        "loadBalancerName": "kato-main-frontend",
        "regions": ["us-east-1", "us-west-1", "us-west-2", "eu-west-1"],
        "credentials": "test"
    }
}]
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|loadBalancerName  | string | true     | The name of the load balancer.
|regions           | array  | true     | An object that provides a named region to array of region names. For example, +["us-east-1", "us-west-1"]+ will inform the deployment engine to delete from those specific regions.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
