===== Delete Security Group Description

====== Key

+deleteSecurityGroupDescription+

====== Description

This description provides the inputs necessary to handle the deletion of a Security Group at Amazon. This is a destructive process, which cannot be reversed.

CAUTION: This operation marks the end of a Security Group's life. The process cannot be undone, and the configuration cannot be reconstituted. A Security Group of the same configuration will need to be recreated from scratch.

====== Example Request Body
[source,javascript]
----
[{
    "deleteSecurityGroupDescription": {
        "securityGroupName": "foo",
        "vpcId": "vpc1",
        "regions": ["us-east-1", "us-west-1", "us-west-2", "eu-west-1"],
        "credentials": "test"
    }
}]
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|securityGroupName | string | true     | The name of the security group.
|vpcId             | string | false    | The id of VPC where the security group should be deleted. It is not needed for EC2 classic or the default VPC.
|regions           | array  | true     | An object that provides a named region to array of region names. For example, +["us-east-1", "us-west-1"]+ will inform the deployment engine to delete from those specific regions.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
