===== Destroy ASG Description

====== Key

+destroyAsgDescription+

====== Description

This description provides the inputs necessary to forcibly destroy a specified AutoScaling group across many regions.

CAUTION: This is a mortal finale to the AutoScaling group's existence. Even if Scaling Policies are suspended, or instances exist within the AutoScaling group, this operation will DEFINITIVELY, IRRECOVERABLY destroy the AutoScaling group.

TIP: Only use this operation if you're expecting that everything (EVERYTHING) in the AutoScaling group will go bye-bye.

====== Example Request Body
[source,javascript]
----
[{
    "destroyAsgDescription": {
        "asgName": "kato-main-v000",
        "regions": ["us-east-1"],
        "credentials": "test"
    }
}]
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|asgName           | string | true     | The name of the asg that the process will delete.
|regions           | array  | true     | The regions in which the specified ASG lives.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
