name: Setup (NodeJS)
description: Installs Node and sets up JS dependencies
author: jcavanagh

inputs:
  project:
    description: Project to setup
    required: true
  node-version:
    description: Node version to set up
    default: 14.21.3

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      if: hashFiles(format('{0}/package.json', inputs.project)) != ''
      with:
        node-version: ${{ inputs.node-version  }}

    - name: Find yarn cache directory
      if: hashFiles(format('{0}/package.json', inputs.project)) != '' && !env.ACT
      id: yarn-cache
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Restore Yarn cache
      uses: actions/cache@v4
      if: hashFiles(format('{0}/package.json', inputs.project)) != '' && !env.ACT
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}/yarn.lock', inputs.project)) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
#
#    - name: Install Yarn dependencies
#      if: hashFiles(inputs.project + '/package.json') != ''
#      shell: bash
#      working-directory: ${{ inputs.project }}
#      run: yarn install --frozen-lockfile
