/*
 * Spinnaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {

	Roles []string `json:"roles,omitempty"`

	AccountNonExpired bool `json:"accountNonExpired,omitempty"`

	LastName string `json:"lastName,omitempty"`

	AllowedAccounts []string `json:"allowedAccounts,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	Email string `json:"email,omitempty"`

	AccountNonLocked bool `json:"accountNonLocked,omitempty"`

	Username string `json:"username,omitempty"`

	Enabled bool `json:"enabled,omitempty"`

	CredentialsNonExpired bool `json:"credentialsNonExpired,omitempty"`

	Authorities []GrantedAuthority `json:"authorities,omitempty"`
}
