pull_request_rules:
  - name: Automatically merge on CI success and review
    conditions:
      - status-success=build
      - "label=ready to merge"
      - "approved-reviews-by=@oss-approvers"
    actions:
      merge:
        method: squash
        strict: smart
      label:
        add: ["auto merged"]
  - name: Automatically merge PRs from maintainers on CI success and review
    conditions:
    - status-success=build
    - "label=ready to merge"
    - "author=@oss-approvers"
    actions:
      merge:
        method: squash
        strict: smart
      label:
        add: ["auto merged"]
  - name: Automatically merge kork autobump PRs on CI success
    conditions:
      - status-success=build
      - "label~=autobump-*"
      - "author:spinnakerbot"
    actions:
      merge:
        method: squash
        strict: smart
      label:
        add: ["auto merged"]
