steps:
- name: gcr.io/spinnaker-marketplace/gradle_cache
  env: ["GRADLE_USER_HOME=/gradle_cache/.gradle"]
  entrypoint: "bash"
  args: ["-c", "./gradlew orca-web:installDist -x test"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/orca:$TAG_NAME", "-f", "Dockerfile.slim", "."]
  env: ["GRADLE_USER_HOME=/gradle_cache/.gradle"]
images:
- gcr.io/$PROJECT_ID/orca:$TAG_NAME
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
