FROM ubuntu:bionic
MAINTAINER sig-platform@spinnaker.io
COPY orca-web/build/install/orca /opt/orca
RUN apt-get update && apt-get -y install openjdk-8-jre-headless wget
RUN adduser --disabled-login --system spinnaker
RUN mkdir plugins && chown -R 102:nogroup plugins
USER spinnaker
CMD ["/opt/orca/bin/orca"]
