FROM alpine:3.11
MAINTAINER sig-platform@spinnaker.io
COPY kayenta-web/build/install/kayenta /opt/kayenta
RUN apk --no-cache add --update bash openjdk8-jre
RUN adduser -D -S spinnaker
RUN mkdir -p /opt/kayenta/plugins && chown -R spinnaker:nogroup /opt/kayenta/plugins
USER spinnaker
CMD ["/opt/kayenta/bin/kayenta"]
