FROM alpine:3.18
RUN apk add --update \
    openjdk17-jre-headless \

RUN apt-get update && apt-get install -y \
  git

LABEL maintainer="sig-platform@spinnaker.io"
ENV GRADLE_USER_HOME /workspace/.gradle
ENV GRADLE_OPTS -Xmx2048m
CMD ./gradlew build --no-daemon -PskipTests
