FROM ubuntu:bionic
MAINTAINER sig-platform@spinnaker.io
COPY fiat-web/build/install/fiat /opt/fiat
RUN apt-get update && apt-get -y install openjdk-11-jre-headless wget
RUN adduser --disabled-login --system spinnaker
USER spinnaker
CMD ["/opt/fiat/bin/fiat"]
