FROM debian:stable-slim

COPY build/webpack /opt/deck/html/

COPY docker /opt/deck/docker

WORKDIR /opt/deck

RUN useradd -m spinnaker -U

USER spinnaker

RUN docker/setup-apache2.sh

CMD docker/run-apache2.sh
