FROM ubuntu:bionic
LABEL maintainer="sig-platform@spinnaker.io"
RUN apt-get update && apt-get -y install curl openjdk-11-jre-headless wget
RUN adduser --system --uid 10111 --group spinnaker
COPY gate-web/build/install/gate /opt/gate
RUN mkdir -p /opt/gate/plugins && chown -R spinnaker:nogroup /opt/gate/plugins
USER spinnaker
HEALTHCHECK CMD curl http://localhost:8084/health | grep UP || exit 1
CMD ["/opt/gate/bin/gate"]
