:doctype: book

image:http://join.spinnaker.io/badge.svg[Slack Status,link=http://join.spinnaker.io]

Spinnaker is a continuous delivery platform for releasing changes with high velocity and confidence.

This repository is used only to store and organize ancillary configuration, build, and testing tools for the Spinnaker project. The core code making up Spinnaker's microservices is found in the other https://github.com/spinnaker[Spinnaker repositories].

= Using Spinnaker

If you are only interested in using Spinnaker, please refer to the main
Spinnaker site and https://www.spinnaker.io/setup/[Installation] guide.

If you want more information on how Spinnaker is designed, see the https://www.spinnaker.io/concepts/[Documentation Overview].

If you're interested in a detailed walkthrough of the Spinnaker systems, check the https://www.spinnaker.io/reference/[Reference Material].

= Setting Up Spinnaker For Development

These instructions cover pulling Spinnaker from source and setting up to run locally against any of the https://www.spinnaker.io/setup/install/providers/#supported-providers[Cloud Providers].

To build from source and run on localhost follow the https://spinnaker.io/guides/developer/getting-set-up/[Developer Setup Guide]
