bash clouddriver/cleanup-config.sh
bash orca/cleanup-config.sh
bash echo/cleanup-config.sh
bash front50/cleanup-config.sh
bash gate/cleanup-config.sh
bash deck/cleanup-config.sh
bash igor/cleanup-config.sh
bash rosco/cleanup-config.sh
bash fiat/cleanup-config.sh
