bash redis/cleanup-components.sh
bash clouddriver/cleanup-components.sh
bash orca/cleanup-components.sh
bash front50/cleanup-components.sh
bash gate/cleanup-components.sh
bash deck/cleanup-components.sh
bash igor/cleanup-components.sh
bash rosco/cleanup-components.sh
bash fiat/cleanup-components.sh
