apply plugin: "java-library"
apply from: "$rootDir/../kotlin.gradle"
apply from: "$rootDir/gradle/detekt.gradle"

dependencies {
  api(platform(project(":spinnaker-dependencies")))
  api "com.google.code.findbugs:jsr305"


  implementation project(":kork-exceptions")
  implementation project(":kork-moniker")
  implementation "org.slf4j:slf4j-api"
  implementation "ch.qos.logback:logback-classic"
  implementation "ch.qos.logback:logback-core"
  implementation "tools.jackson.core:jackson-core"
  implementation "tools.jackson.core:jackson-databind"
  implementation "tools.jackson.dataformat:jackson-dataformat-yaml"
  implementation "org.springframework:spring-core"
  implementation "org.jetbrains:annotations"
  implementation "org.apache.commons:commons-lang3"
}
