FROM ubuntu:jammy
LABEL maintainer="sig-platform@spinnaker.io"
RUN apt-get update && apt-get -y install curl openjdk-17-jre-headless wget
RUN adduser --system --uid 10111 --group spinnaker
COPY kayenta-web/build/install/kayenta /opt/kayenta
RUN mkdir -p /opt/kayenta/plugins && chown -R spinnaker:nogroup /opt/kayenta/plugins
USER spinnaker
HEALTHCHECK CMD curl --fail http://localhost:8090/health
CMD ["/opt/kayenta/bin/kayenta"]
