name: Publish (docker)
description: Publishes Docker containers for a Spinnaker project
author: jcavanagh

inputs:
  project:
    description: Project to publish
    required: true
  push:
    description: Whether to push the build images or not.  e.g. PRs should build, but not push, images
    default: 'false'
  release-train:
    description: Additional tagging for the latest build on a branch
    required: true
  version:
    description: The version to publish
    required: true
  build-command:
    description: Gradle command to run to prepare the container.  Defaults to `:<project>:<project>-web:installDist`.  Set to 'false' to skip build.
  build-args:
    description: Newline-separated list of build args to forward to Docker
  build-url:
    description: Link to build that produced this container
  container-registry:
    description: Destination container registry
    default: us-west2-docker.pkg.dev/spinnaker-monorepo-test/docker
  github-token:
    description: Github token to expose to the build, needed for Packer plugin rate limits
  gar-json-key:
    description: Google Artifact Registry JSON key
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GAR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      # use service account flow defined at: https://github.com/docker/login-action#service-account-based-authentication-1
      with:
        registry: us-west2-docker.pkg.dev
        username: _json_key
        password: ${{ inputs.gar-json-key }}

    - name: Process Inputs
      shell: bash
      run: |
        if [[ '${{ hashFiles(format('{0}/Dockerfile.slim', inputs.project)) }}' != '' ]]; then
          echo "has-slim=true" >> $GITHUB_ENV
        fi
        
        if [[ '${{ hashFiles(format('{0}/Dockerfile.ubuntu', inputs.project)) }}' != '' ]]; then
          echo "has-ubuntu=true" >> $GITHUB_ENV
        fi

    - name: Run build to produce container artifacts
      if: inputs.build-command != 'false'
      env:
        ORG_GRADLE_PROJECT_version: ${{ inputs.version }}
      shell: bash
      run: |
        ./gradlew ${{ !inputs.build-command && format(':{0}:{0}-web:installDist', inputs.project) || inputs.build-command }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        ## Temporary due to bug in qemu:  https://github.com/docker/setup-qemu-action/issues/198
        image: tonistiigi/binfmt:qemu-v7.0.0-28

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Build and publish standard container image
      if: env.has-standard == 'true'
      uses: docker/build-push-action@v6
      id: docker-standard
      env:
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: ${{ inputs.project }}
        file: ${{ inputs.project }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push == 'true' }}
        build-args: ${{ inputs.build-args }}
        secrets: |
          github_token=${{ inputs.github-token }}
        tags: |
          "${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }}"
          "${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.release-train }}-latest"
        labels: |
          "org.opencontainers.image.source=https://github.com/spinnaker/spinnaker"
          "org.opencontainers.image.revision=${{ github.sha }}"
          "org.opencontainers.image.version=${{ inputs.version }}"
          "io.spinnaker.ci-build=${{ inputs.build-url }}"

    - name: Build and publish slim container image
      if: env.has-slim == 'true'
      uses: docker/build-push-action@v6
      id: docker-slim
      env:
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: ${{ inputs.project }}
        file: ${{ inputs.project }}/Dockerfile.slim
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push == 'true' }}
        build-args: ${{ inputs.build-args }}
        secrets: |
          github_token=${{ inputs.github-token }}
        tags: |
          "${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }}"
          "${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }}-slim"
          "${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.release-train }}-latest"
        labels: |
          "org.opencontainers.image.source=https://github.com/spinnaker/spinnaker"
          "org.opencontainers.image.revision=${{ github.sha }}"
          "org.opencontainers.image.version=${{ inputs.version }}"
          "io.spinnaker.ci-build=${{ inputs.build-url }}"

    - name: Build and publish ubuntu container image
      if: env.has-ubuntu == 'true'
      uses: docker/build-push-action@v6
      id: docker-ubuntu
      env:
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: ${{ inputs.project }}
        file: ${{ inputs.project }}/Dockerfile.ubuntu
        platforms: linux/amd64,linux/arm64
        push: ${{ inputs.push == 'true' }}
        build-args: ${{ inputs.build-args }}
        secrets: |
          github_token=${{ inputs.github-token }}
        tags: |
          "${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }}-ubuntu"
        labels: |
          "org.opencontainers.image.source=https://github.com/spinnaker/spinnaker"
          "org.opencontainers.image.revision=${{ github.sha }}"
          "org.opencontainers.image.version=${{ inputs.version }}"
          "io.spinnaker.ci-build=${{ inputs.build-url }}"

    - name: Summarize
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        echo "### Docker Publishing" >> "$GITHUB_STEP_SUMMARY"
        echo "| Type | Image SHA | Tag |" >> "$GITHUB_STEP_SUMMARY"
        echo "| --- | --- | --- |" >> "$GITHUB_STEP_SUMMARY"
        
        if [[ '${{ env.has-standard }}' == 'true' ]]; then
          echo "| __Standard__ | ${{ steps.docker-standard.outputs.imageid }} | ${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "|  |  | ${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.release-train }}-latest |" >> "$GITHUB_STEP_SUMMARY"
        fi
        
        if [[ '${{ env.has-slim }}' == 'true' ]]; then
          echo "| __Slim__ | ${{ steps.docker-slim.outputs.imageid }} | ${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "|  |  | ${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }}-slim |" >> "$GITHUB_STEP_SUMMARY"
          echo "|  |  | ${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.release-train }}-latest |" >> "$GITHUB_STEP_SUMMARY"
        fi
        
        if [[ '${{ env.has-ubuntu }}' == 'true' ]]; then
          echo "| __Ubuntu__ | ${{ steps.docker-ubuntu.outputs.imageid }} | ${{ inputs.container-registry }}/${{ inputs.project }}:${{ inputs.version }}-ubuntu |" >> "$GITHUB_STEP_SUMMARY"
        fi
