FROM alpine:3.24
RUN apk add --update \
    openjdk17 \
    && rm -rf /var/cache/apk
LABEL maintainer="sig-platform@spinnaker.io"
ENV GRADLE_USER_HOME /workspace/.gradle
ENV GRADLE_OPTS -Xmx4g
CMD ./gradlew --no-daemon rosco-web:installDist -x test
