git tag -f clouddriver-main-0
git tag -f deck-main-0
git tag -f deck-kayenta-main-0
git tag -f echo-main-0
git tag -f fiat-main-0
git tag -f front50-main-0
git tag -f gate-main-0
git tag -f halyard-main-0
git tag -f igor-main-0
git tag -f kayenta-main-0
git tag -f keel-main-0
git tag -f kork-main-0
git tag -f orca-main-0
git tag -f rosco-main-0
git tag -f spin-main-0
