module.exports = {
  env: {
    browser: true,
    jasmine: true,
    node: true,
  },
  extends: ['eslint:recommended', 'prettier', 'plugin:@typescript-eslint/recommended'],
  globals: {
    $: 'readonly',
    _: 'readonly',
  },
  ignorePatterns: ['**/*.spec.*', 'template/**/*'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module',
  },
  plugins: ['@spinnaker/eslint-plugin', 'react-hooks'],
  rules: {
    '@spinnaker/api-deprecation': 2,
    '@spinnaker/api-no-slashes': 2,
    '@spinnaker/api-no-unused-chaining': 2,
    '@spinnaker/import-from-alias-not-npm': 2,
    '@spinnaker/import-from-npm-not-alias': 2,
    '@spinnaker/import-from-npm-not-relative': 2,
    '@spinnaker/import-from-presentation-not-core': 2,
    '@spinnaker/import-relative-within-subpackage': 2,
    '@spinnaker/import-sort': 1,
    '@spinnaker/rest-prefer-static-strings-in-initializer': 2,
    '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/ban-types': 'off',
    '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-member-accessibility': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/indent': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-empty-interface': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-parameter-properties': 'off',
    '@typescript-eslint/no-require-imports': 'off',
    '@typescript-eslint/no-this-alias': 'off',
    '@typescript-eslint/no-unused-expressions': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/triple-slash-reference': 'off',
    indent: 'off',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-extra-boolean-cast': 'off',
    'no-prototype-builtins': 'off',
    'one-var': ['error', { initialized: 'never' }],
    'prefer-rest-params': 'off',
    'prefer-spread': 'off',
    'react-hooks/rules-of-hooks': 'error',
    'require-atomic-updates': 'off',
  },
  overrides: [
    {
      files: ['**/*.js', '**/*.jsx'],
      rules: {
        '@typescript-eslint/no-use-before-define': 'off',
      },
    },
    {
      files: ['**/*.ts', '**/*.tsx'],
      rules: {
        'no-undef': 'off',
      },
    },
  ],
};
