FROM ubuntu:resolute
LABEL maintainer="sig-platform@spinnaker.io"
ARG TARGETARCH
ENV GOOGLE_CLOUD_SDK_VERSION=575.0.1
ENV PATH="$PATH:/opt/google-cloud-sdk/bin/"
ENV AWS_CLI_VERSION=2.35.22
ENV AWS_AIM_AUTHENTICATOR_VERSION=0.7.18

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
  curl \
  openjdk-25-jre-headless \
  wget \
  python3-pip \
  python3 \
  git \
  openssh-client \
  unzip && \
  rm -rf ~/.config/gcloud

# AWS CLI 2
RUN if [ "${TARGETARCH}" = "arm64" ]; then \
    wget -nv -O "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-aarch64-${AWS_CLI_VERSION}.zip"; \
  else \
    wget -nv -O "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip"; \
  fi && \
  unzip awscliv2.zip && \
  ./aws/install && \
  rm -rf ./awscliv2.zip ./aws

# kubectl + AWS IAM authenticator
COPY kubectl-versions.json /tmp/kubectl-versions.json
RUN set -eu; \
    KUBECTL_DEFAULT_RELEASE="$(python3 -c 'import json; config = json.load(open("/tmp/kubectl-versions.json")); print(config["versions"][config["defaultMinor"]]["kubectl"])')"; \
    KUBECTL_RELEASES="$(python3 -c 'import json; config = json.load(open("/tmp/kubectl-versions.json")); print(" ".join(version["kubectl"] for version in config["versions"].values()))')"; \
    for version in $KUBECTL_RELEASES; do \
      release_version="${version%.*}"; \
      curl --fail --location --silent --show-error --output "/usr/local/bin/kubectl-${release_version}" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${TARGETARCH}/kubectl"; \
      curl --fail --location --silent --show-error --output /tmp/kubectl.sha512 \
        "https://dl.k8s.io/release/v${version}/bin/linux/${TARGETARCH}/kubectl.sha512"; \
      echo "$(cat /tmp/kubectl.sha512)  /usr/local/bin/kubectl-${release_version}" | sha512sum -c; \
      chmod +x "/usr/local/bin/kubectl-${release_version}"; \
    done; \
    rm -f /tmp/kubectl.sha512 /tmp/kubectl-versions.json; \
    ln -sf "/usr/local/bin/kubectl-${KUBECTL_DEFAULT_RELEASE%.*}" /usr/local/bin/kubectl; \
    wget -nv -O aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${AWS_AIM_AUTHENTICATOR_VERSION}/aws-iam-authenticator_${AWS_AIM_AUTHENTICATOR_VERSION}_linux_${TARGETARCH} \
  && chmod +x ./aws-iam-authenticator \
  && mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator\
  && ln -sf /usr/local/bin/aws-iam-authenticator /usr/local/bin/heptio-authenticator-aws

# Google cloud SDK
RUN [ $TARGETARCH = 'amd64' ] &&  export GCP_ARCH="x86_64" || export GCP_ARCH="arm"  \
  && wget -nv https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-${GCP_ARCH}.tar.gz \
  && mkdir -p /opt && cd /opt \
  && tar -xzf /google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-${GCP_ARCH}.tar.gz \
  && rm /google-cloud-sdk-${GOOGLE_CLOUD_SDK_VERSION}-linux-${GCP_ARCH}.tar.gz \
  && CLOUDSDK_PYTHON="python3" /opt/google-cloud-sdk/install.sh --usage-reporting=false --bash-completion=false  \
     --additional-components app-engine-java app-engine-go gke-gcloud-auth-plugin  \
  && rm -rf ~/.config/gcloud \
  && rm -rf /opt/google-cloud-sdk/.install/.backup


RUN adduser --system --uid 10111 --group spinnaker
COPY clouddriver-web/build/install/clouddriver /opt/clouddriver
RUN mkdir -p /opt/clouddriver/plugins && chown -R spinnaker:nogroup /opt/clouddriver/plugins
USER spinnaker
HEALTHCHECK CMD curl --fail http://localhost:7002/health
CMD ["/opt/clouddriver/bin/clouddriver"]
