dependencies {
  api(project(":keel-retrofit"))
  api("tools.jackson.core:jackson-databind")
  api("com.fasterxml.jackson.core:jackson-annotations")
  api("tools.jackson.module:jackson-module-kotlin")
  api(project(":keel-core-test"))

  implementation("org.junit.jupiter:junit-jupiter-api")
  implementation("com.squareup.retrofit2:retrofit-mock")
  implementation("com.squareup.okhttp3:mockwebserver")
  implementation("dev.minutest:minutest")
  implementation("io.strikt:strikt-jvm")

  implementation("org.jetbrains.kotlin:kotlin-reflect")
}
