===== Enable ASG Description

====== Key

+enableAsgDescription+

====== Description

This description provides the inputs necessary for "enabling" an AutoScaling group. AutoScaling groups are considered enabled when their "Launch", "Terminate", and "AddToLoadBalancer" scaling processes are not suspended. This operation will register instances from the ASG load balancers as well.

NOTE: In addition to enabling an ASG with Amazon, if a Eureka/Discovery host is provided in configuration with the specified account, then this process will put all instances in the ASG +UP+.

====== Example Request Body
[source,javascript]
----
[{
    "enableAsgDescription": {
        "asgName": "kato-main-v000",
        "regions": ["us-west-1", "us-east-1"],
        "credentials": "test"
    }
}]
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|asgName           | string | true     | The name of the asg that the process will enable.
|regions           | array  | true     | The regions in which the specified ASG lives.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
