===== Register Instances with Load Balancer Description

====== Key

+registerInstancesWithLoadBalancerDescription+

====== Description

This description provides the inputs necessary to register the specified instances with all load balancers.

NOTE: If an auto scaling group _is_ specified, instances will be registered with all load balancers associated with that auto scaling group. +
If an auto scaling group _is not_ specified and a list of load balancers _is_ specified, instances will be registered with those load balancers.

====== Example Request Body (specifying all load balancers in an ASG)
[source,javascript]
----
[{
    "registerInstancesWithLoadBalancerDescription": {
        "asgName": "kato-main-v000",
        "instanceIds": ["i-123456", "i-234567"],
        "region": "us-west-1",
        "credentials": "test"
    }
}]
----

====== Example Request Body (specifying selected load balancers)
[source,javascript]
----
[{
    "registerInstancesWithLoadBalancerDescription": {
        "loadBalancerNames": ["kato--frontend"],
        "instanceIds": ["i-123456", "i-234567"],
        "region": "us-west-1",
        "credentials": "test"
    }
}]
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|asgName           | string | false    | The name of the asg in which the instances reside. If not specified, "loadBalancerNames" will be used to determine load balancers to target.
|loadBalancerNames | array  | false    | The load balancers with which the instances will be registered. If not specified, all load balancers associated with the ASG specified in "asgName" will be used.
|instanceIds       | array  | true     | The ids of the instances that are to be registered as part of this operation.
|region            | string | true     | The region in which the instances live.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
