apiVersion: v1
kind: ReplicationController
metadata:
  name: spkr-cassandra-v000
  namespace: spinnaker
spec:
  replicas: 2
  selector:
    replication-controller: spkr-cassandra-v000
  template:
    metadata:
      labels:
        replication-controller: spkr-cassandra-v000
        load-balancer-spkr-cassandra: "true"
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              value: "spinnaker"
            - name: CASSANDRA_SERVICE
              value: "spkr-cassandra"
          image: gcr.io/google-samples/cassandra:v8
          name: cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
