=== Quick Intro

The Spinnaker Java client is designed to utilize the Spinnaker platform through the Spinnaker's gateway API.

==== Getting access to the client

You can use any maven-based dependency manager to get a handler on the Spinnaker Java client. Presently, the artifacts are presently published to Spinnaker's private bintray repository, so that target will need to be specified in build scripts.

> via Gradle for use within a project
```groovy
repositories {
  maven { url "http://dl.bintray.com/spinnaker/spinnaker" }
}
dependencies {
  compile "com.netflix.spinnaker.client:spinnaker-client:0.11"
}
```

> via Gradle for use within the buildscript
```groovy
buildscript {
  repositories {
    maven { url "http://dl.bintray.com/spinnaker/spinnaker" }
  }
  dependencies {
    classpath 'com.netflix.spinnaker.client:spinnaker-client:0.11'
  }
}
```

> via Groovy script (don't use this in Jenkins)
```groovy
@GrabResolver(name='spinnaker', root='http://dl.bintray.com/spinnaker/spinnaker')
@Grab('com.netflix.spinnaker.client:spinnaker-client:0.11')

import com.netflix.spinnaker.client.Spinnaker
// rest of script
```

> via Maven
```xml
<dependency>
  <groupId>com.netflix.spinnaker.client</groupId>
  <artifactId>spinnaker-client</artifactId>
  <version>0.11</version>
</dependency>
```

=== Common Use Cases

Below are some common use cases and example for how to use the client.

==== Listing applications

```groovy
def applications = Spinnaker.using("http://spinnaker-api.prod").applications()
```

==== Getting a specific application

```groovy
def mimirdemo = Spinnaker.using("http://spinnaker-api.prod").application("mimirdemo")
```

==== Create new application

include::client/createNewApp.adoc[]

==== Bake an application

include::client/bakeApp.adoc[]

==== Get Clusters for an Application

include::client/getClusters.adoc[]

=== Examples

=== Simplest Example - Groovy Script

include::client/simplestExample.adoc[]

=== Groovy RxJava DSL Example

include::client/groovyRxJavaDslExample.adoc[]
