===== Destroy ASG Stage

====== Type

+destroyAsg+

====== Description

This stage destroys a named AutoScaling group across many regions.

CAUTION: This is a mortal finale to the AutoScaling group's existence. Even if Scaling Policies are suspended, or instances exist within the AutoScaling group, this operation will DEFINITIVELY, IRRECOVERABLY destroy the AutoScaling group.

TIP: Only use this operation if you're expecting that everything (EVERYTHING) in the AutoScaling group will go bye-bye.

====== Services Involved

_orca_, _kato_, _oort_

====== Steps

_destroyAsg_, _monitorAsg_, _forceCacheRefresh_, _sendNotification_

====== Example Request Body
[source,javascript]
----
{
    "type": "destroyAsg",
    "asgName": "kato-main-v000",
    "regions": ["us-east-1"],
    "credentials": "test"
}
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|asgName           | string | true     | The name of the asg that the process will delete.
|regions           | array  | true     | The regions in which the specified ASG lives.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================

