===== Enable ASG Stage

====== Type

+enableAsg+

====== Description

This stage enables a named AutoScaling group across multiple regions. AutoScaling groups are considered enabled when their "Launch", "Terminate", and "AddToLoadBalancer" scaling processes are not suspended. This operation will allow instances to become registered with an AutoScaling group's configured load balancer. In addition to disabling an ASG with Amazon, if a Eureka/Discovery host is provided in configuration with the specified account, then this process will put all instances in the ASG into +UP+ status.

====== Services Involved

_orca_, _kato_, _oort_

====== Steps

_enableAsg_, _monitorAsg_, _waitForUpInstances_, _sendNotification_

====== Example Request Body
[source,javascript]
----
{
  "type": "enableAsg",
  "asgName": "kato-main-v000",
  "regions": ["us-west-1", "us-east-1"],
  "credentials": "test"
}
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|asgName           | string | true     | The name of the asg that the process will disable.
|regions           | array  | true     | The regions in which the specified ASG lives.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
