= Spinnaker API
Dan Woods <danw@netflix.com>
2014-11-14
:toc: right
:toclevels: 4
:sectanchors:
:sectlink:
:linkattrs:
:numbered:
:appversion: 1.1-SNAPSHOT
:source-highlighter: prettify

== Introduction

Spinnaker's Gateway API service exposes a RESTful HTTP API, where orchestrated stages can be submitted on behalf of an application or in the context of another managed resource (like cluster, server group, or load balancer).

== Spinnaker Java Client

Spinnaker provides a zero-dependency Java client for developers to be able to write applications against the platform.

- - -
include::client.adoc[]
- - -

== Orchestrated Operations

=== Invoking an Operation

Presently, all orchestrated stages need to be scoped to an application, and wrapped in a payload that correlates them to that application. For example, a payload for baking a package for an application might look something like the example depicted in Listing 1.

.Listing 1
[source,javascript]
----
{
    "application": "kato",
    "description": "bake",
    "job": [{
        "type": "bake",
        "region": "us-east-1",
        "user": "orca",
        "package": "kato",
        "baseOs": "ubuntu",
        "baseLabel": "release"
    }]
}
----

This payload should be an HTTP `POST` request to the `/applications/kato/tasks` endpoint of the Spinnaker Gateway API. Since all orchestrations within Spinnaker are asynchronous, this operation will return a task reference, which can be polled for successful completion.

=== Working with Tasks

As noted in the prior section, submission of a set of orchestrated stages will return a reference to a task. The response payload looks like that shown in Listing 1.1.

.Listing 1.1
[source,javascript]
----
{ "ref": "/tasks/1" }
----

The supplied reference path can be queried through an HTTP GET request to produce a Task result graph. A Task result graph will show steps as they are currently executing (it will not show steps that have not executed yet), as well as input and output variables, and task and step execution times. An example task execution graph looks like the JSON depicted in Listing 1.2.

.Listing 1.2
[source,javascript]
----
{
    "id": 402,
    "name": "orca-orchestration-348c6444-0926-4814-b72f-cda8e3e764db",
    "status": "COMPLETED",
    "variables": [{
        "key": "description",
        "value": "Bake (Gate)"
    }, {
        "key": "package",
        "value": "pond"
    }, {
        "key": "baseOs",
        "value": "ubuntu"
    }, {
        "key": "baseLabel",
        "value": "release"
    }, {
        "key": "region",
        "value": "us-east-1"
    }, {
        "key": "user",
        "value": "gate"
    }, {
        "key": "status",
        "value": {
            "id": "s-4skc3aa7p28j1vt75f1bksvwzn",
            "state": "COMPLETED",
            "resourceId": "b-493p0924rg8agtdsr7s32qzs2d"
        }
    }, {
        "key": "ami",
        "value": "ami-xxx"
    }],
    "steps": [{
        "name": "orca-init-step",
        "status": "COMPLETED",
        "startTime": 1415951965957,
        "endTime": 1415951965971
    }, {
        "name": "orca-init-step-2",
        "status": "COMPLETED",
        "startTime": 1415951965973,
        "endTime": 1415951965975
    }, {
        "name": "createBake",
        "status": "COMPLETED",
        "startTime": 1415951965986,
        "endTime": 1415951971626
    }, {
        "name": "monitorBake",
        "status": "COMPLETED",
        "startTime": 1415951971629,
        "endTime": 1415952235550
    }, {
        "name": "completedBake",
        "status": "COMPLETED",
        "startTime": 1415952235553,
        "endTime": 1415952236470
    }],
    "startTime": 1415951965955,
    "endTime": 1415952236472
}
----

The example shown in Listing 1.2 is an example output from a single "bake" stage operation. Stages that are in-flight will return a `status` field of `EXECUTION`, while those that have failed for some reason will show a `status` field of `FAILED`. Failed task will result in a top-level status of `STOPPED`, while those that are presently executing will show as `STARTED`.

=== Stage Chaining

Multiple stages can be chained together to generate an orchestrated execution, where stages may derive some context from the outputs of a preceding stage. The canonical example of this is a bake and deploy Task, where the two stages are submitted as part of the same execution. The deploy stage needn't include the otherwise-required `amiName` field, as it will be able to consume the AMI name from the preceding bake stage.

An example payload of chained stages can be seen in Listing 1.3.

.Listing 1.3
[source,javascript]
----
{
    "application": "kato",
    "description": "bake and deploy",
    "job": [{
        "type": "bake",
        "region": "us-east-1",
        "user": "orca",
        "package": "kato",
        "baseOs": "ubuntu",
        "baseLabel": "release"
    }, {
        "type": "deploy",
        "cluster": {
            "strategy": "redblack",
            "application": "kato",
            "stack": "prestaging",
            "instanceType": "m3.medium",
            "securityGroups": [
                "nf-infrastructure-vpc",
                "nf-datacenter-vpc"
            ],
            "iamRole": "SpinnakerInstanceProfile",
            "subnetType": "internal",
            "availabilityZones": {
                "us-east-1": []
            },
            "capacity": {
                "min": 1,
                "max": 1,
                "desired": 1
            },
            "loadBalancers": [
                "kato-prestaging-frontend"
            ]
        },
        "account": "prod"
    }]
}
----

Stages that are chained will comprise a single execution and will therefore only produce a single Task result and reference. The Task's resulting variables will be the results from all stages.

=== Pipelines

TODO

=== Stages

- - -
include::bakeStage.adoc[]
- - -
include::copyLastAsgStage.adoc[]
- - -
include::deleteAmazonLoadBalancer.adoc[]
- - -
include::deleteLoadBalancer.adoc[]
- - -
include::deleteSecurityGroup.adoc[]
- - -
include::deleteApplicationStage.adoc[]
- - -
include::deployStage.adoc[]
- - -
include::destroyAsgStage.adoc[]
- - -
include::disableAsgStage.adoc[]
- - -
include::enableAsgStage.adoc[]
- - -
include::jenkinsStage.adoc[]
- - -
include::resizeAsgStage.adoc[]
- - -
include::scriptStage.adoc[]
- - -
include::terminateInstancesStage.adoc[]
- - -
include::upsertApplicationStage.adoc[]
- - -
include::upsertAmazonDNSStage.adoc[]
- - -
include::upsertAmazonLoadBalancerStage.adoc[]
- - -
include::upsertSecurityGroupStage.adoc[]
- - -
include::waitStage.adoc[]
- - -

== Accessing Credentials Detail

NOTE: The endpoint mapped to +/credentials+ provides the names of the accounts that are configured within Spinnaker, along with the cloud provider each account is associated with. Descriptions that are POST'ed to an application's Task endpoint may require a credential's name to resolve it internally.

==== Endpoints

[width="100%",frame="topbot",options="header,footer"]
|======================
|Request Type | Endpoint            | Description
|GET          | /credentials        | Returns an array of objects describing the configured credential account names and provider types
|======================

==== Example

.Listing 1.4
[source,javascript]
----
GET /credentials
[
  {
    name: "test",
    type: "aws"
  },
  {
    name: "prod",
    type: "gce"
  }
]
----

== Copyrights and Licenses

Copyright (C) 2014 Netflix. Licensed under the Apache License.

See https://raw.githubusercontent.com/spinnaker/gate/master/LICENSE.txt[LICENSE.txt] for more information.
