===== Modify Scaling Process Stage

====== Type

+modifyScalingProcess+

====== Description

This stage provides the ability to enable or disable autoscaling processes on an Amazon AutoScaling Group.

AutoScaling Process Types:
 * Launch - _Controls if new instances should be launched into the ASG. If this is disabled, scale-up events will not produce new instances._
 * Terminate - _Controls if instances should be terminated during a scale-down event._
 * AddToLoadBalancer - _Controls if new instances should be added to the ASG's ELB._
 * AlarmNotification - _This disables autoscaling._
 * AZRebalance - _Controls whether instances in an Availability Zone should be rebalanced to another zone when the AZ becomes unhealthy._
 * HealthCheck - _If disabled, the instance's health will no longer be reported to the autoscaling processor._
 * ReplaceUnhealthy - _Controls whether instances should be replaced if they failed health check._
 * ScheduledActions - _Controls whether scheduled actions should be executed._

====== Services Involved

_orca_, _kato_, _oort_

====== Steps

_suspendScalingProcess_, _monitorKato_ *or* _resumeScalingProcess_, _monitorKato_

====== Example Request Body
[source,javascript]
----
{
  "type": "modifyScalingProcess",
  "action": "resume",
  "processes": ["Terminate"],
  "asgName": "kato-main-v000",
  "regions": ["us-west-1", "us-east-1"],
  "credentials": "test"
}
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|action            | string | true     | The modification action to perform. One of: +suspend+, +resume+
|processes         | array  | true     | The processes that should be disabled for this ASG.
|asgName           | string | true     | The name of the asg on which the processes will be disabled.
|regions           | array  | true     | The regions in which the specified ASG lives.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
