===== Register Instances with Load Balancer Stage

====== Type

+registerInstancesWithLoadBalancer+

====== Description

This stage orchestrates registering a number of named instances with all load balancers associated with the specified auto scaling group. All instances must exist within the provided region.

NOTE: If no auto scaling group is specified, the ASG associated with each instance will be used.

====== Services Involved

_orca_, _kato_, _oort_

====== Steps

_registerInstances_, _monitorInstances_, _waitForLoadBalancerState_

====== Example Request Body
[source,javascript]
----
{
  "type": "registerInstancesWithLoadBalancer",
  "asgName": "kato-main-v000",
  "instanceIds": ["i-123456", "i-234567"],
  "region": "us-east-1",
  "credentials": "test"
}
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|asgName           | string | false    | The name of the asg in which the instances reside.
|instanceIds       | array  | true     | The ids of the instances that are to be registered as part of this operation.
|region            | string | true     | The region in which the instances live.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
