===== Terminate Instances Stage

====== Type

+terminateInstances+

====== Description

This stage orchestrates the termination of a number of named instances within a region. This is a totally destructive operation, and the instance ids that are supplied to this operation cannot be reconstituted in any way whatsoever.

====== Services Involved

_orca_, _kato_, _oort_

====== Steps

_terminateInstances_, _monitorTermination_, _waitForTerminatedInstances_, _sendNotification_

====== Example Request Body
[source,javascript]
----
{
  "type": "terminateInstances",
  "instanceIds": ["i-123456", "i-234567"],
  "region": "us-east-1",
  "credentials": "test"
}
----

====== Description of inputs

[width="100%",frame="topbot",options="header,footer"]
|======================
|Key               | Type   | Required | Value
|instanceIds       | array  | true     | The ids of the instances that are to be terminated as part of this operation.
|region            | string | true     | The region in which the instances live.
|credentials       | string | true     | The named account credentials that are to be used for this operation.
|======================
