heat_template_version: 2015-04-30
description: Auto scaling group for Spinnaker
parameters:
  flavor:
    type: string
    description: flavor used by the web servers
  image:
    type: string
    description: Image used for servers
  internal_port:
    type: string
    description: internal app port for each server
  max_size:
    type: number
    description: maximum cluster size
  min_size:
    type: number
    description: minimum cluster size
  network_id:
    type: string
    description: Network used by the servers
  pool_id:
    type: string
    description: Load balancer to use for this group
  security_groups:
    type: comma_delimited_list
    description: security groups to use
resources:
  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: {get_param: min_size}
      max_size: {get_param: max_size}
      resource:
        type: asg_resource.yaml
        properties:
          flavor: {get_param: flavor}
          image: {get_param: image}
          internal_port: {get_param: internal_port}
          # TODO this is here for demo purposes - will need to figure if this shoudl be parameterized
          metadata: {"metering.stack": {get_param: "OS::stack_id"}}
          network_id: {get_param: network_id}
          pool_id: {get_param: pool_id}
          security_groups: {get_param: security_groups}
  # TODO parameterize
  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: 1
  # TODO parameterize
  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: -1
outputs:
  OS::stack_id:
    value: {get_resource: asg}
  scale_up_url:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaleup_policy, alarm_url]}
  scale_dn_url:
    description: >
      This URL is the webhook to scale down the autoscaling group.
      You can invoke the scale-down operation by doing an HTTP POST to
      this URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaledown_policy, alarm_url]}
  asg_size:
    description: >
      This is the current size of the auto scaling group.
    value: {get_attr: [asg, current_size]}
