heat_template_version: 2016-04-08
description: An auto-scaled server for Spinnaker without any load balancer association.
parameters:
  flavor:
    type: string
    description: Flavor used by the servers.
  image:
    type: string
    description: Image used for servers.
  metadata:
    type: json
    description: Server instance metadata.
  network_id:
    type: string
    description: Network used by each server. Retained for auditing purposes.
  security_groups:
    type: comma_delimited_list
    description: Security groups associate to each server.
  subnet_id:
    type: string
    description: Subnet used to allocate a fixed IP for each server.
  user_data:
    type: string
    description: Raw base64-encoded string that will execute upon server boot, if cloud-init is installed.
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      metadata: {get_param: metadata}
      networks:
        - subnet: {get_param: subnet_id}
      security_groups: {get_param: security_groups}
      user_data: {get_param: user_data}
      user_data_format: RAW

outputs:
  server_ip:
    description: IP Address of the load-balanced server
    value: { get_attr: [server, first_address] }
