artifacts:
  git-repo:
    enabled: true
    git-executable: ${GIT_WRAPPER}
    accounts:
      - name: basic-auth
        username: test
        password: test
      - name: token-auth
        token: ${gitea_token}
      - name: ssh-auth
        sshPrivateKeyFilePath: ${ssh_key_file}
        sshPrivateKeyPassphrase: ${ssh_key_pass}
        sshTrustUnknownHosts: true
      - name: ssh-auth-known-hosts
        sshPrivateKeyFilePath: ${ssh_key_file}
        sshPrivateKeyPassphrase: ${ssh_key_pass}
        sshTrustUnknownHosts: false
        sshKnownHostsFilePath: ${known_hosts}

logging.level.com.netflix.spinnaker.clouddriver.artifacts.gitRepo: DEBUG

spring:
  application:
    name: clouddriver

sql:
  enabled: true
  taskRepository:
    enabled: true
  cache:
    enabled: true
    readBatchSize: 500
    writeBatchSize: 300
  scheduler:
    enabled: true
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&
    tasks:
      jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&
  migration:
    jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&

redis:
  enabled: false
  cache:
    enabled: false
  scheduler:
    enabled: false
  taskRepository:
    enabled: false

services:
  fiat:
    baseUrl: http://fiat.net
  front50:
    baseUrl: http://front50.net
