== Cloud Foundry on clouddriver

=== Developing clouddriver-cf

Need to run clouddriver locally for development? Here's what you need to setup and run:

. git clone git@github.com:spinnaker/clouddriver.git
. mkdir ~/.spinnaker
. cd ~/.spinnaker
. ln -s /path/to/clouddriver/clouddriver-web/config/clouddriver.yml
. cd /path/to/clouddriver
. CF_ENABLED=true CF_ACCOUNT_NAME=<your_cf_username> CF_PASSWORD=<your_cf_password> CF_API=<your_cf_api_endpoint> ./gradlew bootRun
. curl -v localhost:7002/applications

You can also run the `Main` in clouddriver-web with the same environment settings shown above. Then poke at localhost:7002/applications in your browser.

NOTE: Get the https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en[Chrome] or https://addons.mozilla.org/en-us/firefox/addon/jsonview/[Firefox] plugin to make JSON data easy to view.

With this setup, you can also switch to running it in debug mode inside your IDE to test out various bits.

=== Running CloudDriver on a CF setup

CloudDriver isn't built as a Spring Boot uber JAR. Instead, NetFlix bundles it up into a Debian package. Nonetheless, the CloudFoundry Java buildpack can handle this.

. ./gradlew clean buildDeb
. Log into the CF environment where you want to host Spinnaker services. (NOTE: This is NOT the CF environment you monitor and deploy built artifacts.)
. cf push clouddriver -p clouddriver-web/build/install/clouddriver/

After this deploys, if it's the first time, will fail on startup. You need to configure some properties:

* CF_ENABLED - true
* CF_API - API URL for the instance of CF you are targeting
* CF_ACCOUNT_NAME - your CF username
* CF_PASSWORD - your CF password

Restart the app and monitor it's logs. After a certain amount of time (1-2 minutes), visit <clouddriver-url>/applications and you should see a detailed listing of all the applications in your CF instance.

=== Serving up CloudDriver through the Gate API

While you don't need to make any edits to NetFlix's gate service, it is needed to serve data to the UI.

. git clone git@github.com:spinnaker/gate.git
. ./gradlew clean buildDeb
. Log into the CF environment where you want to host Spinnaker services. (NOTE: This is NOT the CF environment you monitor and deploy built artifacts.)
. cf push gate -p gate-web/build/install/gate/

=== Viewing application data on the web

To run the frontend UI, follow these steps:

. git clone git@github.com:spinnaker/deck.git
. cd deck
. ./gradlew clean build
. cf push deck -p build/webpack/ -b staticfile_buildpack

This will push the static assets in their built/minimized form. Then set some env variables:

* API_HOST - the URL for Gate app hosted earlier (without the 'http://' prefix)
* PROTOCOL - *http*