buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'org.testcontainers:testcontainers:2.0.5'
  }
}

import org.testcontainers.containers.GenericContainer
import org.testcontainers.utility.DockerImageName

sourceSets {
  integrationTest {
    java {
      compileClasspath += main.output + test.output
      runtimeClasspath += main.output + test.output
      srcDir file('src/integration-test/java')
    }
    resources.srcDir file('src/integration-test/resources')
  }
}

configurations {
  integrationTestCompile.extendsFrom testImplementation
  integrationTestRuntime.extendsFrom testRuntime
}

//noinspection GroovyAssignabilityCheck
task startEmbeddedRedis() {
  group 'Application'
  description 'Starts an embedded Valkey server on an open port.'

  doLast {
    def redisContainer = new GenericContainer(DockerImageName.parse("valkey/valkey:8"))
            .withExposedPorts(6379)
    redisContainer.start()
    startEmbeddedRedis.ext.redisContainer = redisContainer
    startEmbeddedRedis.ext.redisPort = redisContainer.getMappedPort(6379)
  }
}

//noinspection GroovyAssignabilityCheck
task stopEmbeddedRedis() {
  dependsOn startEmbeddedRedis
  group 'Application'
  description 'Stops the embedded Valkey server.'

  doLast {
    startEmbeddedRedis.ext.redisContainer.stop()
  }
}

//noinspection GroovyAssignabilityCheck
task integrationTest(type: Test) {
  useJUnitPlatform()
  doFirst {
    systemProperty("redis.port", startEmbeddedRedis.ext.redisPort)
  }
  systemProperty("spring.application.name", "kayenta")
  systemProperty('spring.config.name', "spinnaker,kayenta")
  systemProperty('spring.config.location', "file:${project.rootDir}/kayenta-signalfx/src/integration-test/resources/config/")
  testClassesDirs = sourceSets.integrationTest.output.classesDirs
  classpath = sourceSets.integrationTest.runtimeClasspath
}

tasks.integrationTest.dependsOn 'startEmbeddedRedis'
tasks.integrationTest.finalizedBy 'stopEmbeddedRedis'

integrationTest {
  testLogging {
    showStandardStreams = true
  }
}

configurations {
  integrationTestImplementation.extendsFrom configurations.testImplementation
  integrationTestRuntime.extendsFrom configurations.testRuntime
}

dependencies {
  implementation project(":kayenta-core")

  testImplementation project(":kayenta-standalone-canary-analysis")
  testImplementation "com.squareup.retrofit2:converter-jackson"
  testImplementation "com.squareup.okhttp3:mockwebserver"
  // Integration Test dependencies
  integrationTestImplementation sourceSets.main.output
  integrationTestImplementation sourceSets.test.output
  integrationTestImplementation project(':kayenta-web')
  integrationTestImplementation "com.squareup.okhttp3:mockwebserver"
  integrationTestRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
  integrationTestRuntimeOnly "org.junit.platform:junit-platform-launcher"

  // Apache 2.0 https://github.com/rest-assured/rest-assured/blob/master/LICENSE
  integrationTestImplementation "io.rest-assured:rest-assured"

  integrationTestAnnotationProcessor platform("io.spinnaker.orca:orca-bom")
  integrationTestAnnotationProcessor "org.projectlombok:lombok"
  integrationTestCompileOnly "org.projectlombok:lombok"
}

configurations {
  integrationTestImplementation.extendsFrom testImplementation
  integrationTestImplementation.extendsFrom testRuntime
}

test {
  testLogging {
    events "passed", "skipped", "failed"
  }
}
