FROM alpine:3.24
RUN apk add --update \
    openjdk17-jre-headless \
    git \
    && rm -rf /var/cache/apk

LABEL maintainer="sig-platform@spinnaker.io"
ENV GRADLE_USER_HOME /workspace/.gradle
ENV GRADLE_OPTS -Xmx2048m
CMD ./gradlew build --no-daemon -PskipTests
