apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - serviceaccount.ym l
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: igor
configMapGenerator:
  - name: igor
