FROM ubuntu:jammy
LABEL maintainer="sig-platform@spinnaker.io"
RUN rm /var/lib/dpkg/info/libc-bin.* && apt-get clean && apt-get update && apt-get -y install curl openjdk-17-jre-headless wget
RUN adduser --system --uid 10111 --group spinnaker
COPY orca-web/build/install/orca /opt/orca
RUN mkdir -p /opt/orca/plugins && chown -R spinnaker:nogroup /opt/orca/plugins
USER spinnaker
HEALTHCHECK CMD curl --fail http://localhost:8083/health
CMD ["/opt/orca/bin/orca"]
