steps:
  - id: buildCompileImage
    waitFor: ["-"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "compile", "-f", "Dockerfile.compile", "."]
  - id: buildSlimImage
    waitFor: ["buildCompileImage"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-slim", "-f", "Dockerfile.slim", "."]
  - id: buildUbuntuImage
    waitFor: ["buildCompileImage"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-ubuntu", "-f", "Dockerfile.ubuntu", "."]
  - id: tagDefaultImage
    waitFor: ["buildSlimImage"]
    name: gcr.io/cloud-builders/docker
    args: ["tag", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-slim", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]
images:
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-slim
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-ubuntu
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8