# Copyright 2018 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This is the base configuration for the buildtool assembling Spinnaker GA
# releases. It can also serve as a template for custom configurations.
#
# To customize:
#    You can inherit defaults from this file by adding a "defaults_arg_file"
#    that references this one. However it is probably not a good idea to do
#    this against this GA file due to long term maintainence changes.
#    As new parameters are added, you might unintentionally pick up these
#    GA defaults rather than adding new custom ones.
#
#    However, depending on your needs, it could be a good idea to layer
#    your own using data inheritance just introducing the overrides into
#    individual use-case files. In this scenario, it might make sense to
#    straight copy/paste this file into a "baseline.yml" that could be
#    used to diff against this original ga-defaults.yml in the future to
#    easily see what changed since your last baseline rather than having
#    diff against the corresponding commit hash in a git repository.
#
# Commented values surrounded by '<>' are meta-values only for clarity.
# Commented values surrounded by '[]' are code defaults.
# Not all code defaults are shown, only those for commenting purposes.


#################################
# Standard/global configuration
#################################
# default_args_file:
# log_level: info
# input_dir: source_code
# output_dir: output
# one_at_a_time: false
# parent_invocation_id: <unique string>


##########################
# Common "build" options
##########################
# build_number: <generated YYYYMMDDHHSSMM>
# delete_existing: false
# skip_existing: false


#################################
# Metrics Configuration
#################################
# monitoring_enabled: true
# monitoring_flush_frequency: 15
# monitoring_system: file


################################
# Git Publishing Configuration
################################
# git_allow_publish_master_branch: true
# git_never_push: false


################################
# Git Clone Configuration
################################
# github_owner: 
# github_pull_ssh: false
# github_push_ssh: true
# github_disable_upstream_push: false


################################
# Bom Configuration
# (commands that use boms)
################################
# bom_path:
# bom_version:


################################
# Branch Configuration
# (commands that use git branches)
################################
# git_branch: master
# git_fallback_branch: master


###################################
# Spinnaker Release Configuration
# (commands that use spinnaker releases)
###################################
# spinnaker_verison:


################################
# Hal Configuration
################################
# hal_path: /usr/local/bin/hal
# halyard_daemon: localhost:8064


################################
# Gradle Configuration
################################
# bintray_jar_repository:
# gradle_cache_path: environ('HOME')/.gradle
# maven_custom_init_file: spinnaker/dev/maven-init.gradle
# bintray_org:
# bintray_debian_repository:
# max_local_builds:
# run_unit_tests: false


################################
# API Docs Commands
################################
### "build" only
# max_wait_secs_startup: 210
# swagger_codegen_cli_jar_path:


################################
# Bom Commands
################################
#### "build" only
# NOTE: the bom_dependencies_path defaults to
#       spinnaker/dev/buildtool/bom-dependencies.yml
#       if no refresh bom is defined, otherwise dependencies come from the
#       refresh bom unless overriden by an explicit bom_dependencies_path
#       (to refresh from bom)
# bom_dependencies_path:
# refresh_from_bom_path:
# refresh_from_bom_version:
#### "publish" only
# halyard_bom_bucket: halconfig
# bom_alias:


################################
# Changelog Commands
################################
### "build" only
# include_changelog_details: false


################################
# Container Commands
################################
# docker_registry:
# container_env_vars: GRADLE_USER_HOME=/gradle_cache/.gradle
# container_builder: gcb
# gcb_project:
# gcb_service_account:
# container_base_image:
# force_clean_gradle_cache: true


################################
# Halyard Commands
################################
# halyard_version_commits_url:
# halyard_bucket_base_url:
### "build" only
# halyard_docker_image_base
### "publish" only
# halyard_version
# docs_repo_owner:


################################
# Image Commands
################################
# halyard_release_track: stable
# build_gce_service_account:
# build_gce_project:
# build_gce_zone: us-central1-f
# install_image_script: spinnaker/dev/halyard_install_component.sh
# publish_gce_image_script: spinnaker/google/dev/publish_gce_release.sh


################################
# Publish Spinnaker (release)
################################
# spinnaker_release_alias:
# min_halyard_version:

