package com.netflix.spinnaker.keel.actuation

object ResourceCheckCompleted

object ScheduledEnvironmentCheckStarting

object ScheduledEnvironmentVerificationStarting

object ScheduledArtifactCheckStarting
