version: "2"

run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
  exclusions:
    paths:
      - gateapi

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/spinnaker/spin
