import { CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENTSTAGE } from './canaryDeploymentStage';
import { CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENTEXECUTIONDETAILS_CONTROLLER } from './canaryDeploymentExecutionDetails.controller';
('use strict');

const angular = require('angular');

export const CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENT_MODULE = 'spinnaker.canary.canaryDeployment';
export const name = CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENT_MODULE; // for backwards compatibility
angular.module(CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENT_MODULE, [
  CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENTSTAGE,
  CANARY_CANARY_CANARYDEPLOYMENT_CANARYDEPLOYMENTEXECUTIONDETAILS_CONTROLLER,
]);
