spring:
  application:
    name: clouddriver

kubernetes:
  kubectl:
    executable: ${IT_BUILD_HOME}/kubectl
  enabled: true
  primaryAccount: account1
  accounts:
    - name: account1
      cacheIntervalSeconds: 5
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      configureImagePullSecrets: true
      cacheThreads: 3
      namespaces:
        - default
        - account1-testns00
        - account1-testns01
        - account1-testns02
        - account1-testns03
        - account1-testns04
      omitNamespaces: []
      kinds:
        - pod
        - replicaset
        - deployment
        - service
        - configmap
        - secret
        - networkpolicy
        - cronjob
      omitKinds: []
      customResources: []
      cachingPolicies: []
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: true
      metrics: false
      kubeconfigFile: ${IT_BUILD_HOME}/kubecfg.yml  # File is automatically created at runtime
    - name: account2
      cacheIntervalSeconds: 5
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces:
        - account2-testns00
      omitNamespaces: []
      kinds:
        - pod
        - replicaset
        - deployment
        - service
        - configmap
        - secret
        - networkpolicy
        - cronjob
      omitKinds: []
      customResources: []
      cachingPolicies: []
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: true
      metrics: false
      kubeconfigFile: ${IT_BUILD_HOME}/kubecfg.yml  # File is automatically created at runtime

logging.level.com.netflix.spinnaker.cats.sql.cluster: INFO
logging.level.com.netflix.spinnaker.clouddriver.kubernetes.caching.agent.KubernetesCacheDataConverter: WARN

sql:
  enabled: true
  taskRepository:
    enabled: true
  cache:
    enabled: true
    readBatchSize: 500
    writeBatchSize: 300
  scheduler:
    enabled: true
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&
    tasks:
      jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&
  migration:
    jdbcUrl: jdbc:tc:mysql:5.7.22://somehostname:someport/clouddriver?user=root?password=&

redis:
  enabled: false
  cache:
    enabled: false
  scheduler:
    enabled: false
  taskRepository:
    enabled: false

services:
  fiat:
    baseUrl: http://fiat.net
  front50:
    baseUrl: http://front50.net
