FROM alpine:3.20
RUN apk add --update \
    openjdk11 \
    && rm -rf /var/cache/apk
LABEL maintainer="sig-platform@spinnaker.io"
ENV GRADLE_USER_HOME /workspace/.gradle
ENV GRADLE_OPTS -Xmx4g
CMD ./gradlew -PenableCrossCompilerPlugin=true --no-daemon echo-web:installDist -x test
