---
apiVersion: v1
kind: Namespace
metadata:
  name: '${ namespace }'
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: 'backend-${ canary ? "canary" : "primary" }'
  namespace: '${ namespace }'
  labels:
    stack: backend
    tier: '${ namespace }'
    canary: '${ canary ? "true" : "false" }'
spec:
  replicas: '${ #toInt( canary ? 1 : 5 ) }'
  selector:
    matchLabels:
      stack: backend
      tier: '${ namespace }'
      canary: '${ canary ? "true" : "false" }'
  template:
    metadata:
      labels:
        stack: backend
        tier: '${ namespace }'
        canary: '${ canary ? "true" : "false" }'
    spec:
      containers:
      - name: primary
        image: gcr.io/{%PROJECT_ID%}/backend
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: '${ namespace }'
spec:
  selector:
    stack: backend
    tier: '${ namespace }'
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
