# This file is intended to serve as a master configuration for a Spinnaker
# deployment. Customizations to the deployment should be made in another file
# named "spinnaker-local.yml". The distribution has a prototype called
# "default-spinnaker-local.yml" which calls out the subset of attributes of
# general interest. It can be copied into a "spinnaker-local.yml" to start
# with. The prototype does not change any of the default values here, it just
# surfaces the more critical attributes.

global:
  spinnaker:
    environment: test
    timezone: 'America/Los_Angeles'

services:
  default:
    # These defaults can be modified to change all the spinnaker subsystems
    # (clouddriver, gate, etc) at once, but not external systems (jenkins, etc).
    # Individual systems can still be overridden using their own section entry
    # directly under 'services'.
    host: localhost
    protocol: http
    primaryAccountName: service-default-primaryAccountName-not-defined
    dnsSuffix: spinnaker.svc.cluster.local

  clouddriver:
    port: 7002
    address: 0.0.0.0
    mutate:
      host: spin-clouddriver-mutate.${services.default.dnsSuffix}
      port: ${services.clouddriver.port}
      baseUrl: ${services.default.protocol}://${services.clouddriver.mutate.host}:${services.clouddriver.mutate.port}
    ro:
      host: spin-clouddriver-ro.${services.default.dnsSuffix}
      port: ${services.clouddriver.port}
      baseUrl: ${services.default.protocol}://${services.clouddriver.ro.host}:${services.clouddriver.ro.port}
    cache:
      host: spin-clouddriver-cache.${services.default.dnsSuffix}
      port: ${services.clouddriver.port}
      baseUrl: ${services.default.protocol}://${services.clouddriver.cache.host}:${services.clouddriver.cache.port}
    aws:
      udf:
        # Controls whether UserDataProviders are used to populate user data of
        # new server groups. If false, user data is copied over from ancestor
        # server groups on both CopyLastAsgAtomicOperation and
        # ModifyAsgLaunchConfigurationOperation (only if no user data is
        # provided on the given request).
        enabled: true

  echo:
    enabled: true
    port: 8089
    address: 0.0.0.0
    sched:
      host: spin-echo-sched.${services.default.dnsSuffix}
      port: ${services.echo.port}
      baseUrl: ${services.default.protocol}://${services.echo.sched.host}:${services.echo.sched.port}
    event:
      host: spin-echo-event.${services.default.dnsSuffix}
      port: ${services.echo.port}
      baseUrl: ${services.default.protocol}://${services.echo.event.host}:${services.echo.event.port}

    # Persistence mechanism to use
    cassandra:
      enabled: false
    inMemory:
      enabled: true

    cron:
      # Allow pipeline triggers to run periodically via cron expressions.
      enabled: true
      timezone: ${global.spinnaker.timezone}

    notifications:
      # The following blocks can enable Spinnaker to send notifications
      # using the corresponding mechanism.
      # See http://www.spinnaker.io/docs/notifications-and-events-guide
      # for more information.
      mail:
        enabled: false
        host: # the smtp host
        fromAddress: # the address for which emails are sent from
      hipchat:
        enabled: false
        url: # the hipchat server to connect to
        token: # the hipchat auth token
        botName: # the username of the bot
      sms:
        enabled: false
        account: # twilio account id
        token: # twilio auth token
        from: # phone number by which sms messages are sent
      slack:
        enabled: false
        token: # the API token for the bot
        botName: # the username of the bot

  deck:
    host: spin-deck.${services.default.dnsSuffix}
    port: 9000
    baseUrl: ${services.default.protocol}://${services.deck.host}:${services.deck.port}
    gateUrl: ${services.gate.baseUrl}
    bakeryUrl: ${services.bakery.baseUrl}
    timezone: ${global.spinnaker.timezone}
    auth:
      enabled: false

  fiat:
    enabled: false
    address: 0.0.0.0
    host: spin-fiat-ro.${services.default.dnsSuffix}
    port: 7003
    baseUrl: ${services.default.protocol}://${services.fiat.host}:${services.fiat.port}

  front50:
    host: spin-front50.${services.default.dnsSuffix}
    address: 0.0.0.0
    port: 8080
    baseUrl: ${services.default.protocol}://${services.front50.host}:${services.front50.port}

    # If using storage bucket persistence (gcs or s3), specify the bucket here
    # disable cassandra and enable the storage service below.
    storage_bucket:
    # (GCS Only) Location for bucket.
    bucket_root: front50

    cassandra:
      enabled: false
    redis:
      enabled: false
    gcs:
      enabled: false
      project:
      bucket_location:
    s3:
      enabled: false

  gate:
    address: 0.0.0.0
    host: ${services.default.host}
    port: 8084
    baseUrl: ${services.default.protocol}://${services.gate.host}:${services.gate.port}

  igor:
    # If you are integrating Jenkins then you must also enable Spinnaker's
    # "igor" subsystem.
    address: 0.0.0.0
    enabled: false
    host: spin-igor.${services.default.dnsSuffix}
    port: 8088
    baseUrl: ${services.default.protocol}://${services.igor.host}:${services.igor.port}

  orca:
    host: spin-orca.${services.default.dnsSuffix}
    port: 8083
    address: 0.0.0.0
    baseUrl: ${services.default.protocol}://${services.orca.host}:${services.orca.port}
    timezone: ${global.spinnaker.timezone}
    enabled: true

  rosco:
    host: spin-rosco.${services.default.dnsSuffix}
    port: 8087
    address: 0.0.0.0
    baseUrl: ${services.default.protocol}://${services.rosco.host}:${services.rosco.port}
    # You need to provide the fully-qualified path to the directory containing the packer templates.
    # They typically live in rosco's config/packer directory.
    configDir: /opt/rosco/config/packer

  bakery:
    host: ${services.rosco.host}
    port: ${services.rosco.port}
    baseUrl: ${services.rosco.baseUrl}
    extractBuildDetails: true
    allowMissingPackageInstallation: false

  dockerRegistry:
    # This signals to igor to poll on your configured docker registries for the
    # sake of triggering pipelines to deploy newly minted images.
    enabled: true

  jenkins:
    # The "name" entry is used for the display name when selecting
    # this server. You must set `enabled` to true when enabling igor.
    #
    # If you have multiple jenkins servers, you will need to list
    # them in an igor-local.yml. See jenkins.masters in config/igor.yml.
    #
    # Note that jenkins is not installed with Spinnaker so you must obtain this
    # on your own if you are interested.
    enabled: false
    defaultMaster:
      name: Jenkins
      baseUrl:   # Expected in spinnaker-local.yml
      username:  # Expected in spinnaker-local.yml
      password:  # Expected in spinnaker-local.yml

  redis:
    port: 6379
    clouddriver:
      master:
        host: redis-clouddriver-master.${services.default.dnsSuffix}
        connection: redis://${services.redis.clouddriver.master.host}:${services.redis.port}
      slave:
        host: redis-clouddriver-slave.${services.default.dnsSuffix}
        connection: redis://${services.redis.clouddriver.slave.host}:${services.redis.port}
    orca:
      master:
        host: redis-orca-master.${services.default.dnsSuffix}
        connection: redis://${services.redis.orca.master.host}:${services.redis.port}
    igor:
      master:
        host: redis-igor-master.${services.default.dnsSuffix}
        connection: redis://${services.redis.igor.master.host}:${services.redis.port}
    rosco:
      master:
        host: redis-rosco-master.${services.default.dnsSuffix}
        connection: redis://${services.redis.rosco.master.host}:${services.redis.port}
    gate:
      master:
        host: redis-gate-master.${services.default.dnsSuffix}
        connection: redis://${services.redis.gate.master.host}:${services.redis.port}
    fiat:
      master:
        host: redis-fiat-master.${services.default.dnsSuffix}
        connection: redis://${services.redis.fiat.master.host}:${services.redis.port}

providers:
  aws:
    # For more information on configuring Amazon Web Services (aws), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-amazon-web-services-setup

    enabled: false
    simpleDBEnabled: false
    defaultRegion: us-east-1
    defaultSimpleDBDomain: CLOUD_APPLICATIONS
    primaryCredentials:
      name: default
      # The actual credentials are set using a standard AWS client library mechanism
      # http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html
      # Typically this is a $HOME/.aws/credentials file (remember, a standard
      # spinnaker installation runs as user "spinnaker" whose $HOME is
      # /home/spinnaker). The primaryCredentials.name will identify which profile
      # to use (for .aws/credentials).

    # {{name}} will be interpolated with the aws account name (e.g. "my-aws-account-keypair").
    defaultKeyPairTemplate: "{{name}}-keypair"

  google:
    # For more information on configuring Google Cloud Platform (google), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-google-cloud-platform-setup

    enabled: false
    defaultRegion: us-central1
    defaultZone: us-central1-f
    primaryCredentials:
      name: my-account-name
      # The project is the Google Project ID for the project to manage with
      # Spinnaker. The jsonPath is a path to the JSON service credentials
      # downloaded from the Google Developer's Console.
      project:
      jsonPath:

  cf:
    # For more information on configuring Cloud Foundry (cf) support, see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-cloud-foundry-platform-setup

    enabled: false
    defaultOrg: spinnaker-cf-org
    defaultSpace: spinnaker-cf-space
    primaryCredentials:
      name: my-cf-account
      api: my-cf-api-uri
      console: my-cf-console-base-url
      # You must also supply cf.account.username and cf.account.password through env properties

  azure:
    # For more information on configuring Microsoft Azure (azure), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-azure-cloud-platform-setup

    enabled: false
    defaultRegion: westus
    primaryCredentials:
      name: my-azure-account

      # To set Azure credentials, enter your Azure supscription values for:
      # clientId, appKey, tenantId, and subscriptionId.
      clientId:
      appKey:
      tenantId:
      subscriptionId:

  titan:
    # If you want to deploy some services to titan,
    # set enabled and provide primary credentials for deploying.
    # Enabling titan is independent of other providers.
    enabled: false
    defaultRegion: us-east-1
    primaryCredentials:
      name: my-titan-account

  kubernetes:
    # For more information on configuring Kubernetes clusters (kubernetes), see
    # http://www.spinnaker.io/v1.0/docs/target-deployment-setup#section-kubernetes-cluster-setup

    # NOTE: enabling kubernetes also requires enabling dockerRegistry.
    enabled: false
    primaryCredentials:
      name: my-kubernetes-account
      namespace: default
      dockerRegistryAccount: ${providers.dockerRegistry.primaryCredentials.name}

  dockerRegistry:
    # If you want to use a container based provider, you need to configure and
    # enable this provider to cache images.
    enabled: false
    primaryCredentials:
      name: my-docker-registry-account
      address: https://index.docker.io/
      repository: library/nginx
