<VirtualHost {%DECK_HOST%}:{%DECK_PORT%}>
  SSLEngine on
  SSLCertificateFile "{%DECK_CERT_PATH%}"
  SSLCertificateKeyFile "{%DECK_KEY_PATH%}"

  DocumentRoot /opt/deck/html
  FallbackResource /index.html

  ProxyPass "/gate" "{%API_HOST%}" retry=0
  ProxyPassReverse "/gate" "{%API_HOST%}"

  ErrorLog /dev/stderr
  TransferLog /dev/stdout

  <Directory "/opt/deck/html/">
    Require all granted
  </Directory>
</VirtualHost>
