# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "local-simpledb"
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  #need this line? nameserver 10.64.48.160 in the sudo vi /etc/resolv.conf file

  config.vm.box = "ubuntu.13.10-64bit"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision "docker" do |docker|
      docker.run "aws-simpledb-local", image: "aglover/simpledb-pier", args: "-p  8080:8080"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080

end
