import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_CONFIGURATION_SERVICE } from './configuration.service';
import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_COMMANDBUILDER } from './CommandBuilder';
import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_BASICSETTINGS_CONTROLLER } from './wizard/BasicSettings.controller';
import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_ADVANCEDSETTINGS_CONTROLLER } from './wizard/advancedSettings.controller';
import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_CLONE_CONTROLLER } from './wizard/Clone.controller';
import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_VOLUMES_CONTROLLER } from './wizard/volumes.controller';
import { KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_DEPLOYMENT_CONTROLLER } from './wizard/deployment.controller';
('use strict');

import { module } from 'angular';

export const KUBERNETES_V1_SERVERGROUP_CONFIGURE_CONFIGURE_KUBERNETES_MODULE =
  'spinnaker.serverGroup.configure.kubernetes';
export const name = KUBERNETES_V1_SERVERGROUP_CONFIGURE_CONFIGURE_KUBERNETES_MODULE; // for backwards compatibility
module(KUBERNETES_V1_SERVERGROUP_CONFIGURE_CONFIGURE_KUBERNETES_MODULE, [
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_CONFIGURATION_SERVICE,
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_COMMANDBUILDER,
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_BASICSETTINGS_CONTROLLER,
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_ADVANCEDSETTINGS_CONTROLLER,
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_CLONE_CONTROLLER,
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_VOLUMES_CONTROLLER,
  KUBERNETES_V1_SERVERGROUP_CONFIGURE_WIZARD_DEPLOYMENT_CONTROLLER,
]);
