spring:
  application:
    name: gate

services:
  clouddriver:
    baseUrl: http://localhost:7002
  deck:
    baseUrl: http://localhost:9000
  echo:
    enabled: false
    baseUrl: http://localhost:8089
  fiat:
    enabled: false
    baseUrl: http://localhost:8080
  front50:
    baseUrl: http://localhost:8080
  igor:
    enabled: false
  kayenta:
    enabled: false
  rosco:
    enabled: false
  orca:
    baseUrl: http://localhost:8083
  mine:
    enabled: false
  swabbie:
    enabled: false
  keel:
    enabled: false
    baseUrl: http://localhost:8087

slack:
  token: test-token
  baseUrl: https://test-slack-url.com
