FROM python:3.14-alpine3.24
LABEL maintainer="sig-platform@spinnaker.io"
ARG TARGETARCH

ENV KUBECTL_RELEASE=1.30.14
ENV AWS_IAM_AUTHENTICATOR_VERSION=0.7.18

RUN apk --no-cache add --update \
      bash \
      curl \
      openjdk17-jre \
      openssl \
      aws-cli \
  && rm -rf /var/cache/apk

RUN echo '#!/usr/bin/env bash' > /usr/local/bin/hal && \
  echo '/opt/halyard/bin/hal "$@"' >> /usr/local/bin/hal && \
  chmod +x /usr/local/bin/hal

RUN curl -f -LO --retry 3 --retry-delay 3 https://dl.k8s.io/release/v${KUBECTL_RELEASE}/bin/linux/${TARGETARCH}/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

RUN curl -f -Lo /usr/local/bin/aws-iam-authenticator \
    https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${AWS_IAM_AUTHENTICATOR_VERSION}/aws-iam-authenticator_${AWS_IAM_AUTHENTICATOR_VERSION}_linux_${TARGETARCH} && \
  chmod +x /usr/local/bin/aws-iam-authenticator

RUN addgroup -S -g 1000 spinnaker
RUN adduser -S -G spinnaker -u 1000 spinnaker
COPY halyard-web/build/install/halyard /opt/halyard
USER spinnaker

HEALTHCHECK CMD curl http://localhost:8064/health | grep UP || exit 1

CMD ["/opt/halyard/bin/halyard"]
