# .github/workflows/gcr-cleaner.yml
name: 'gcr-cleaner'

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation
    inputs:
      dry-run:
        description: 'Preview deletions without actually deleting images'
        type: boolean
        default: true

jobs:
  ghcr-cleaner:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - clouddriver
          - deck
          - echo
          - fiat
          - front50
          - gate
          - halyard
          - igor
          - kayenta
          - keel
          - orca
          - rosco
    concurrency:
      group: ghcr-cleanup-manager-spinnaker-${{ matrix.package }}
    steps:
      # delete untagged images older than 48 hours
      - name: Clean images
        uses: ghcr-manager/ghcr-cleanup-manager@v1.1.12
        with:
          command: cleanup
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: spinnaker
          package: ${{ matrix.package }}
          delete-untagged: true
          older-than: 48 hours
          dry-run: ${{ github.event.inputs.dry-run != 'false' }}

  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      # configure based on your registry
      - name: Login to GAR
        uses: 'docker/login-action@v4'
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}


      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install gcr-cleaner-cli
        run: go install github.com/GoogleCloudPlatform/gcr-cleaner/cmd/gcr-cleaner-cli@latest

      # delete untaggd images older than 48 hours
      - name: Clean images
        run: |
          $(go env GOPATH)/bin/gcr-cleaner-cli \
            -repo=us-docker.pkg.dev/spinnaker-community/docker \
            -grace=48h \
            -dry-run=${{ github.event.inputs.dry-run != 'false' }}
