name: Deck
run-name: Deck ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_call:
    inputs:
      publish-containers:
        description: Publish containers
        type: boolean
        default: true
      publish-debs:
        description: Publish debs
        type: boolean
        default: true
      publish-npm:
        description: Publish npm
        type: boolean
        default: true
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  workflow_dispatch:
    inputs:
      publish-containers:
        description: Publish containers
        type: boolean
        default: true
      publish-debs:
        description: Publish debs
        type: boolean
        default: true
      publish-npm:
        description: Publish npm
        type: boolean
        default: true
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  push:
    branches:
      - release-*
    paths:
      - 'deck/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'deck/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generic-build-publish
        with:
          project: deck
          docker-build-command: ':deck:webpack'
          publish: ${{ github.event_name != 'pull_request' }}
          publish-containers: ${{ github.event_name == 'push' || inputs.publish-containers == true }}
          publish-debs: ${{ inputs.publish-debs == true }}
          publish-npm: ${{ github.event_name == 'push' || inputs.publish-npm == true }}
          version-override: ${{ inputs.version-override }}
          integration-test: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
          gar-npm-password: ${{ secrets.GAR_NPM_PASSWORD }}
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
