name: Kayenta
run-name: Kayenta ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_call:
    inputs:
      publish-containers:
        description: Publish containers
        type: boolean
        default: true
      publish-debs:
        description: Publish debs
        type: boolean
        default: true
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  workflow_dispatch:
    inputs:
      publish-containers:
        description: Publish containers
        type: boolean
        default: true
      publish-debs:
        description: Publish debs
        type: boolean
        default: true
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  push:
    branches:
      - main
      - release-*
    paths:
      - 'kayenta/**'
      - 'fiat/**'
      - 'kork/**'
      - 'orca/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'kayenta/**'
      - 'fiat/**'
      - 'kork/**'
      - 'orca/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generic-build-publish
        with:
          project: kayenta
          gradle-cmd-opts: -PenableCrossCompilerPlugin=true
          publish: ${{ github.event_name != 'pull_request' }}
          publish-containers: ${{ github.event_name == 'push' || inputs.publish-containers == true }}
          publish-debs: ${{ inputs.publish-debs == true }}
          version-override: ${{ inputs.version-override }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
