name: Spinnaker BoM/Changelog/Github Release
run-name: Spinnaker BoM/Changelog/Github (${{ inputs.spinnaker-version }})

on:
  workflow_call:
    inputs:
      add-to-versions-yml:
        description: Add this version to `versions.yml` for Halyard?
        type: boolean
        default: true
      spinnaker-version:
        description: The Spinnaker version to publish a BoM/changelog for
        type: string
        required: true
      spinnaker-previous-version:
        description: Override the previous version used for changelog generation (picks the last patch version if unset)
        type: string
      publish-bom:
        description: Publish BoM?
        type: boolean
        default: true
      publish-changelog:
        description: Publish changelog?
        type: boolean
        default: true
      publish-github-release:
        description: Publish Github release?
        type: boolean
        default: true
      allow-bom-overwrite:
        description: Allow BoM overwrite if it already exists?
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      add-to-versions-yml:
        description: Add this version to `versions.yml` for Halyard?
        type: boolean
        default: true
      spinnaker-version:
        description: The Spinnaker version to publish a BoM/changelog for
        type: string
        required: true
      spinnaker-previous-version:
        description: Override the previous version used for changelog generation (picks the last patch version if unset)
        type: string
      publish-bom:
        description: Publish BoM?
        type: boolean
        default: true
      publish-changelog:
        description: Publish changelog?
        type: boolean
        default: true
      publish-github-release:
        description: Publish Github release?
        type: boolean
        default: true
      allow-bom-overwrite:
        description: Allow BoM overwrite if it already exists?
        type: boolean
        default: false

jobs:
  check-preconditions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Exit if not on a release branch
        run: |
          REF="${{ github.ref_name }}"
          
          if  [[ $REF != release-* ]]; then
            echo "Release workflow must be run from a release branch"
            exit 1
          fi

      - name: Generate version to verify
        id: precondition-version
        uses: ./.github/actions/version
        with:
          namespace: spinnaker
          is-release: true
          skip-increment: true
          skip-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check branch matches desired version
        run: |
          REF="${{ github.ref_name }}"
          REQUIRED_REF='release-${{ steps.precondition-version.outputs.release-train-suffixed }}'
          
          if [[ $REF != $REQUIRED_REF ]]; then
            echo "Wrong release branch - please run from $REQUIRED_REF"
            exit 1
          fi

  spinnaker-release-bom:
    runs-on: ubuntu-latest
    needs: check-preconditions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Spinnaker release BoM and changelog
        id: spinnaker-release-bom
        uses: ./.github/actions/spinnaker-release
        with:
          github-pat: ${{ secrets.SPINNAKERBOT_PERSONAL_ACCESS_TOKEN }}
          credentials-json: ${{ secrets.GAR_JSON_KEY }}
          version: ${{ inputs.spinnaker-version }}
          previous-version: ${{ inputs.spinnaker-previous-version }}
          add-to-versions-yml: ${{ inputs.add-to-versions-yml }}
          publish-bom: ${{ inputs.publish-bom }}
          publish-changelog: ${{ inputs.publish-changelog }}
          allow-bom-overwrite: ${{ inputs.allow-bom-overwrite }}

      - name: Create Github release
        if: inputs.publish-github-release == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: spinnaker-release-${{ inputs.spinnaker-version }}
          release_name: Spinnaker ${{ inputs.spinnaker-version }}
          body: |
            ${{ steps.spinnaker-release-bom.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Summarize
        shell: bash
        run: |
          echo "### Release Info" >> "$GITHUB_STEP_SUMMARY"
          echo "| | |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | --- |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __Version__ | ${{ inputs.spinnaker-version }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __BoM__ | ${{ steps.spinnaker-release-bom.outputs.bom-url }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __Changelog__ | ${{ steps.spinnaker-release-bom.outputs.bom-url }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __versions.yml__ | ${{ steps.spinnaker-release-bom.outputs.versions-yml-url }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>BoM Contents</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.spinnaker-release-bom.outputs.bom }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>Changelog Contents</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.spinnaker-release-bom.outputs.changelog }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>versions.yml Contents</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.spinnaker-release-bom.outputs.versions-yml }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
