name: Spinnaker Libraries
run-name: Libraries ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  workflow_dispatch:
    inputs:
      version-override:
        description: Overrides the version for artifacts (e.g. "1.37.1").  Otherwise, uses the auto-incrementing build number for the current branch.
        type: string

  push:
    branches:
      - main
      - release-*
    paths:
      - 'clouddriver/**'
      - 'echo/**'
      - 'fiat/**'
      - 'front50/**'
      - 'gate/**'
      - 'halyard/**'
      - 'igor/**'
      - 'kayenta/**'
      - 'keel/**'
      - 'kork/**'
      - 'orca/**'
      - 'rosco/**'

jobs:
  libraries-nexus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/version
        id: version
        with:
          namespace: spinnaker-libraries
          version-override: ${{ inputs.version-override }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v5
        with:
          java-version: |
            17
          distribution: zulu
          cache: ${{ !env.ACT && 'gradle' || '' }} # Disable Gradle cache when running actions locally

      - name: Publish Nexus libraries
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.version.outputs.version }}
          ORG_GRADLE_PROJECT_nexusPublishEnabled: true
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_nexusPgpSigningKey: ${{ secrets.NEXUS_PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_nexusPgpSigningPassword: ${{ secrets.NEXUS_PGP_SIGNING_PASSWORD }}
        run: |
          ./gradlew assemble publishToNexus closeAndReleaseNexusStagingRepository
