SET tx_isolation = 'READ-COMMITTED';

CREATE SCHEMA `echo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER echo_migrate;
CREATE USER echo_service;

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON `echo`.* TO 'echo_service'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, SHOW VIEW ON `echo`.* TO 'echo_migrate'@'%';
